### ISSUE TITLE
502 (Bad Gateway) on server calls from container

### ISSUE THREAD

**Issue by zonggen** [coreos/fcct-online#6]
`Failed to load resource: the server responded with a status of 502 (Bad Gateway)` on server calls when using images pulled from quay.io but normal (status 200) when using local built image.

Might be related to nginx config, currently investigating..

**Comment by zonggen** [comment]
`gunicorn -b 127.0.0.1:5000 app:app --daemon --log-file logfile ` outputs log to `logfile`:
```
[2019-08-09 13:56:42 +0000] [10] [INFO] Starting gunicorn 19.9.0
[2019-08-09 13:56:42 +0000] [10] [INFO] Listening at: http://127.0.0.1:5000 (10)
[2019-08-09 13:56:42 +0000] [10] [INFO] Using worker: sync
[2019-08-09 13:56:42 +0000] [21] [INFO] Booting worker with pid: 21
[2019-08-09 13:57:01 +0000] [21] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.6/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 37, in fcc_to_ignition
    stdin=PIPE, stdout=PIPE, stderr=STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './fcct-x86_64-unknown-linux-gnu': './fcct-x86_64-unknown-linux-gnu'
```

I forgot to run setup script in container :(
Updating soon

[EDIT]:
 - Updated and fixed, closing
